language: scala
scala:
 - 2.13.0-RC3
 - 2.12.8
 - 2.11.12
jdk: openjdk8
env:
 - WEBDRIVER_CHROME_DRIVER="/usr/lib/chromium-browser/chromedriver"
 - WEBDRIVER_GECKO_DRIVER="/usr/lib/geckodriver/geckodriver"
script:
 - sbt ++$TRAVIS_SCALA_VERSION test
 - sbt ++$TRAVIS_SCALA_VERSION inttest
addons:
 chrome: stable
 firefox: latest
 apt:
  packages:
    - chromium-chromedriver
before_install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
 - mkdir /usr/lib/geckodriver
 - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C /usr/lib/geckodriver
